name: cuidaper_mobile
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_modular: ^4.3.1
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2
  asuka: ^2.0.0
  dio: ^4.0.4
  flutter_screenutil: ^5.0.1+3
  flutter_dotenv: ^5.0.2
  logger: ^1.1.0
  shared_preferences: ^2.0.12
  flutter_secure_storage: ^5.0.2
  validatorless: ^1.2.1
  
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  firebase_remote_config: ^1.0.4
  firebase_messaging: ^11.2.5
  
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

  fonts:
    - family: CuidapetIcons
      fonts:
        - asset: assets/fonts/CuidapetIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
